# CodeRabbit 설정 파일
# 문서: https://docs.coderabbit.ai/getting-started/configure-coderabbit/

# 언어 설정 - 한글로 리뷰 출력
language: "ko-KR"

# 리뷰 동작 설정
reviews:
  # PR 블로킹 없이 제안만 제공
  request_changes_workflow: false
  
  # PR 상단에 전체 요약 제공
  high_level_summary: true
  
  # 시 생성 비활성화 (전문성 유지)
  poem: false
  
  # 리뷰 진행 상태 표시
  review_status: true
  
  # 상세 설명은 펼쳐진 상태로 표시
  collapse_walkthrough: false
  
  # 자동 리뷰 설정
  auto_review:
    enabled: true
    # Draft PR도 리뷰
    drafts: false

# 파일별 설정
path_filters:
  # 테스트 파일은 덜 엄격하게 검토
  - path: "src/test/**"
    instructions:
      - "테스트 커버리지와 엣지 케이스를 중점적으로 검토해주세요"
      - "JUnit 5 best practices를 따르는지 확인해주세요"
  
  # 문서는 맞춤법과 명확성 위주로 검토
  - path: "**/*.md"
    instructions:
      - "문서의 명확성과 완성도를 검토해주세요"
      - "한글 맞춤법과 기술 용어의 일관성을 확인해주세요"

# 프로젝트별 리뷰 지침
instructions:
  - "이 프로젝트는 Java 기반 LLM 라이브러리입니다"
  - "Spring Boot 및 Spring Framework에서의 통합을 중점적으로 검토해주세요"
  - "CompletableFuture와 Reactor Core를 사용한 비동기 처리를 확인해주세요"
  - "웹 애플리케이션에서 LLM 호출 시 발생할 수 있는 문제점을 지적해주세요"
  - "특히 다음 사항들을 검토해주세요:"
  - "  - 긴 실행 시간으로 인한 타임아웃 문제"
  - "  - 메모리 사용량과 리소스 관리"
  - "  - 스레드 안전성과 동시성 처리"
  - "  - 에러 핸들링과 재시도 로직"
  - "  - 스트리밍 응답 처리 방식 (Flux/Publisher)"
  - "MCP(Model Context Protocol) 통합 시 리소스 정리가 적절히 되는지 확인해주세요"
  - "Immutables 라이브러리 사용이 적절한지 검토해주세요"
  - "Builder 패턴과 Fluent API가 일관성 있게 구현되었는지 확인해주세요"
  - "Java 8+ 호환성을 유지하는지 검토해주세요"

# 검토에서 제외할 파일/폴더
path_exclusions:
  - "**/build/**"
  - "**/.gradle/**"
  - "**/gradle/wrapper/**"
  - "**/*.class"
  - "**/target/**"
  - "**/.idea/**"
  - "**/*.iml"
  - "**/out/**"
  - "**/bin/**"
  - "**/.settings/**"
  - "**/.classpath"
  - "**/.project"

# 추가 도구 설정
tools:
  # GitHub Actions 통합
  github_actions:
    enabled: true
  
  # 정적 분석 도구
  checkstyle:
    enabled: true
  
  # SpotBugs (FindBugs 후속)
  spotbugs:
    enabled: true

# 리뷰 우선순위
review_priority:
  # 중요 파일 우선 검토
  - "src/main/java/kr/pyhub/llm/base/BaseLLM.java"
  - "src/main/java/kr/pyhub/llm/LLM.java"
  - "src/main/java/kr/pyhub/llm/mcp/**"
  - "src/main/java/kr/pyhub/llm/providers/**"
  - "build.gradle"

# 라벨 자동 추가
labels:
  - "enhancement": "새로운 기능이 추가된 경우"
  - "bug": "버그 수정이 포함된 경우"
  - "documentation": "문서만 변경된 경우"
  - "breaking-change": "하위 호환성이 깨지는 변경사항이 있는 경우"
  - "performance": "성능 개선이 포함된 경우"
  - "dependencies": "의존성이 변경된 경우"